// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 환경 변수 - Vite와 Next.js 모두 지원
const SUPABASE_URL = 
  process.env.NEXT_PUBLIC_SUPABASE_URL || 
  import.meta.env?.VITE_SUPABASE_URL || 
  '';

/**
 * Supabase "공개(anon) 키" 환경변수
 *
 * Supabase 공식 용어는 보통 ANON_KEY 이지만,
 * 이 프로젝트는 과거 문서에서 PUBLISHABLE_KEY 라는 이름을 사용한 이력이 있어
 * 배포/로컬에서 둘 중 아무 키로 설정해도 동작하도록 호환성을 유지합니다.
 */
const SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env?.VITE_SUPABASE_ANON_KEY ||
  import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
  '';

// 환경 변수 검증
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    '❌ Supabase 환경 변수가 설정되지 않았습니다.\n' +
    '배포(Vercel)라면 Vercel 프로젝트 → Settings → Environment Variables에 값을 등록한 뒤 "Redeploy"가 필요합니다.\n' +
    '로컬 개발이라면 프로젝트 루트에 .env.local 또는 .env 파일을 생성하고 다음 중 하나를 추가하세요:\n\n' +
    '【Next.js】\n' +
    'NEXT_PUBLIC_SUPABASE_URL=https://your-project-id.supabase.co\n' +
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key\n' +
    '(또는 NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key)\n\n' +
    '【Vite】\n' +
    'VITE_SUPABASE_URL=https://your-project-id.supabase.co\n' +
    'VITE_SUPABASE_ANON_KEY=your_supabase_anon_key\n' +
    '(또는 VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key)'
  );
} else {
  console.log('✅ Supabase 연결:', SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_ANON_KEY || 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
      },
    },
    db: {
      schema: 'public',
    },
  }
);